export default {
  classifications: {
    'Ceramics': '🍶',
    'Glass': '🔮',
    'Paintings': '🎨',
    'Furniture': '🛋️',
    'Metalwork': '⚙️',
    'Sculpture': '🗿',
    'Arms and Armor': '⚔️',
    'Architecture': '🏛️',
    'Other': '❓'
  },
  countries: {
    'Austria': '🇦🇹',
    'Belgium': '🇧🇪',
    'China': '🇨🇳',
    'England': '🇬🇧',
    'France': '🇫🇷',
    'Germany': '🇩🇪',
    'Greece': '🇬🇷',
    'India': '🇮🇳',
    'Italy': '🇮🇹',
    'Japan': '🇯🇵',
    'Mexico': '🇲🇽',
    'Netherlands': '🇳🇱',
    'Spain': '🇪🇸',
    'Turkey': '🇹🇷',
    'United States': '🇺🇸'
  },
  other: [
    'Miniatures',
    'Jewelry',
    'Tools/Equipment/Utensils',
    'Enamels',
    'Lighting',
    'Jades and other stones',
    'Stained Glass',
    'Ivory/Horn/Bone/Shell',
    'Costume (including accessories)',
    'Timepieces',
    'Frames',
    'Textiles',
    'Containers - Wood',
    'Toys (including dolls, games, puppets)',
    'Books',
    'Manuscripts',
    'Photographs',
    'Wallpaper',
    'Drawings',
    'Lacquer',
    'Fiber Art',
    'Prints',
    'Coins and Medals',
    'Calligraphy',
    'Musical Instruments'
  ],
  emojis: {
    "100":"💯",
    "1234":"🔢",
    "interrobang":"⁉️",
    "tm":"™️",
    "information_source":"ℹ️",
    "left_right_arrow":"↔️",
    "arrow_up_down":"↕️",
    "arrow_upper_left":"↖️",
    "arrow_upper_right":"↗️",
    "arrow_lower_right":"↘️",
    "arrow_lower_left":"↙️",
    "keyboard":"⌨",
    "sunny":"☀️",
    "cloud":"☁️",
    "umbrella":"☔️",
    "showman":"☃",
    "comet":"☄",
    "ballot_box_with_check":"☑️",
    "coffee":"☕️",
    "shamrock":"☘",
    "skull_and_crossbones":"☠",
    "radioactive_sign":"☢",
    "biohazard_sign":"☣",
    "orthodox_cross":"☦",
    "wheel_of_dharma":"☸",
    "white_frowning_face":"☹",
    "aries":"♈️",
    "taurus":"♉️",
    "sagittarius":"♐️",
    "capricorn":"♑️",
    "aquarius":"♒️",
    "pisces":"♓️",
    "spades":"♠️",
    "clubs":"♣️",
    "hearts":"♥️",
    "diamonds":"♦️",
    "hotsprings":"♨️",
    "hammer_and_pick":"⚒",
    "anchor":"⚓️",
    "crossed_swords":"⚔",
    "scales":"⚖",
    "alembic":"⚗",
    "gear":"⚙",
    "scissors":"✂️",
    "white_check_mark":"✅",
    "airplane":"✈️",
    "email":"✉️",
    "envelope":"✉️",
    "black_nib":"✒️",
    "heavy_check_mark":"✔️",
    "heavy_multiplication_x":"✖️",
    "star_of_david":"✡",
    "sparkles":"✨",
    "eight_spoked_asterisk":"✳️",
    "eight_pointed_black_star":"✴️",
    "snowflake":"❄️",
    "sparkle":"❇️",
    "question":"❓",
    "grey_question":"❔",
    "grey_exclamation":"❕",
    "exclamation":"❗️",
    "heavy_exclamation_mark":"❗️",
    "heavy_heart_exclamation_mark_ornament":"❣",
    "heart":"❤️",
    "heavy_plus_sign":"➕",
    "heavy_minus_sign":"➖",
    "heavy_division_sign":"➗",
    "arrow_heading_up":"⤴️",
    "arrow_heading_down":"⤵️",
    "wavy_dash":"〰️",
    "congratulations":"㊗️",
    "secret":"㊙️",
    "copyright":"©️",
    "registered":"®️",
    "bangbang":"‼️",
    "leftwards_arrow_with_hook":"↩️",
    "arrow_right_hook":"↪️",
    "watch":"⌚️",
    "hourglass":"⌛️",
    "fast_forward":"⏩",
    "rewind":"⏪",
    "arrow_double_up":"⏫",
    "arrow_double_down":"⏬",
    "black_right_pointing_double_triangle_with_vertical_bar":"⏭",
    "black_left_pointing_double_triangle_with_vertical_bar":"⏮",
    "black_right_pointing_triangle_with_double_vertical_bar":"⏯",
    "alarm_clock":"⏰",
    "stopwatch":"⏱",
    "timer_clock":"⏲",
    "hourglass_flowing_sand":"⏳",
    "double_vertical_bar":"⏸",
    "black_square_for_stop":"⏹",
    "black_circle_for_record":"⏺",
    "m":"Ⓜ️",
    "black_small_square":"▪️",
    "white_small_square":"▫️",
    "arrow_forward":"▶️",
    "arrow_backward":"◀️",
    "white_medium_square":"◻️",
    "black_medium_square":"◼️",
    "white_medium_small_square":"◽️",
    "black_medium_small_square":"◾️",
    "phone":"☎️",
    "telephone":"☎️",
    "point_up":"☝️",
    "star_and_crescent":"☪",
    "peace_symbol":"☮",
    "yin_yang":"☯",
    "relaxed":"☺️",
    "gemini":"♊️",
    "cancer":"♋️",
    "leo":"♌️",
    "virgo":"♍️",
    "libra":"♎️",
    "scorpius":"♏️",
    "recycle":"♻️",
    "wheelchair":"♿️",
    "atom_symbol":"⚛",
    "fleur_de_lis":"⚜",
    "warning":"⚠️",
    "zap":"⚡️",
    "white_circle":"⚪️",
    "black_circle":"⚫️",
    "coffin":"⚰",
    "funeral_urn":"⚱",
    "soccer":"⚽️",
    "baseball":"⚾️",
    "snowman":"⛄️",
    "partly_sunny":"⛅️",
    "thunder_cloud_and_rain":"⛈",
    "ophiuchus":"⛎",
    "pick":"⛏",
    "helmet_with_white_cross":"⛑",
    "chains":"⛓",
    "no_entry":"⛔️",
    "shinto_shrine":"⛩",
    "church":"⛪️",
    "mountain":"⛰",
    "umbrella_on_ground":"⛱",
    "fountain":"⛲️",
    "golf":"⛳️",
    "ferry":"⛴",
    "boat":"⛵️",
    "sailboat":"⛵️",
    "skier":"⛷",
    "ice_skate":"⛸",
    "person_with_ball":"⛹",
    "tent":"⛺️",
    "fuelpump":"⛽️",
    "fist":"✊",
    "hand":"✋",
    "raised_hand":"✋",
    "v":"✌️",
    "writing_hand":"✍",
    "pencil2":"✏️",
    "latin_cross":"✝",
    "x":"❌",
    "negative_squared_cross_mark":"❎",
    "arrow_right":"➡️",
    "curly_loop":"➰",
    "loop":"➿",
    "arrow_left":"⬅️",
    "arrow_up":"⬆️",
    "arrow_down":"⬇️",
    "black_large_square":"⬛️",
    "white_large_square":"⬜️",
    "star":"⭐️",
    "o":"⭕️",
    "part_alternation_mark":"〽️",
    "mahjong":"🀄️",
    "black_joker":"🃏",
    "a":"🅰️",
    "b":"🅱️",
    "o2":"🅾️",
    "parking":"🅿️",
    "ab":"🆎",
    "cl":"🆑",
    "cool":"🆒",
    "free":"🆓",
    "id":"🆔",
    "new":"🆕",
    "ng":"🆖",
    "ok":"🆗",
    "sos":"🆘",
    "up":"🆙",
    "vs":"🆚",
    "koko":"🈁",
    "sa":"🈂️",
    "u7121":"🈚️",
    "u6307":"🈯️",
    "u7981":"🈲",
    "u7a7a":"🈳",
    "u5408":"🈴",
    "u6e80":"🈵",
    "u6709":"🈶",
    "u6708":"🈷️",
    "u7533":"🈸",
    "u5272":"🈹",
    "u55b6":"🈺",
    "ideograph_advantage":"🉐",
    "accept":"🉑",
    "cyclone":"🌀",
    "foggy":"🌁",
    "closed_umbrella":"🌂",
    "night_with_stars":"🌃",
    "sunrise_over_mountains":"🌄",
    "sunrise":"🌅",
    "city_sunset":"🌆",
    "city_sunrise":"🌇",
    "rainbow":"🌈",
    "bridge_at_night":"🌉",
    "ocean":"🌊",
    "volcano":"🌋",
    "milky_way":"🌌",
    "earth_africa":"🌍",
    "earth_americas":"🌎",
    "earth_asia":"🌏",
    "globe_with_meridians":"🌐",
    "new_moon":"🌑",
    "waxing_crescent_moon":"🌒",
    "first_quarter_moon":"🌓",
    "moon":"🌔",
    "waxing_gibbous_moon":"🌔",
    "full_moon":"🌕",
    "waning_gibbous_moon":"🌖",
    "last_quarter_moon":"🌗",
    "waning_crescent_moon":"🌘",
    "crescent_moon":"🌙",
    "new_moon_with_face":"🌚",
    "first_quarter_moon_with_face":"🌛",
    "last_quarter_moon_with_face":"🌜",
    "full_moon_with_face":"🌝",
    "sun_with_face":"🌞",
    "star2":"🌟",
    "stars":"🌠",
    "thermometer":"🌡",
    "mostly_sunny":"🌤",
    "sun_small_cloud":"🌤",
    "barely_sunny":"🌥",
    "sun_behind_cloud":"🌥",
    "partly_sunny_rain":"🌦",
    "sun_behind_rain_cloud":"🌦",
    "rain_cloud":"🌧",
    "snow_cloud":"🌨",
    "lightning":"🌩",
    "lightning_cloud":"🌩",
    "tornado":"🌪",
    "tornado_cloud":"🌪",
    "fog":"🌫",
    "wind_blowing_face":"🌬",
    "hotdog":"🌭",
    "taco":"🌮",
    "burrito":"🌯",
    "chestnut":"🌰",
    "seedling":"🌱",
    "evergreen_tree":"🌲",
    "deciduous_tree":"🌳",
    "palm_tree":"🌴",
    "cactus":"🌵",
    "hot_pepper":"🌶",
    "tulip":"🌷",
    "cherry_blossom":"🌸",
    "rose":"🌹",
    "hibiscus":"🌺",
    "sunflower":"🌻",
    "blossom":"🌼",
    "corn":"🌽",
    "ear_of_rice":"🌾",
    "herb":"🌿",
    "four_leaf_clover":"🍀",
    "maple_leaf":"🍁",
    "fallen_leaf":"🍂",
    "leaves":"🍃",
    "mushroom":"🍄",
    "tomato":"🍅",
    "eggplant":"🍆",
    "grapes":"🍇",
    "melon":"🍈",
    "watermelon":"🍉",
    "tangerine":"🍊",
    "lemon":"🍋",
    "banana":"🍌",
    "pineapple":"🍍",
    "apple":"🍎",
    "green_apple":"🍏",
    "pear":"🍐",
    "peach":"🍑",
    "cherries":"🍒",
    "strawberry":"🍓",
    "hamburger":"🍔",
    "pizza":"🍕",
    "meat_on_bone":"🍖",
    "poultry_leg":"🍗",
    "rice_cracker":"🍘",
    "rice_ball":"🍙",
    "rice":"🍚",
    "curry":"🍛",
    "ramen":"🍜",
    "spaghetti":"🍝",
    "bread":"🍞",
    "fries":"🍟",
    "sweet_potato":"🍠",
    "dango":"🍡",
    "oden":"🍢",
    "sushi":"🍣",
    "fried_shrimp":"🍤",
    "fish_cake":"🍥",
    "icecream":"🍦",
    "shaved_ice":"🍧",
    "ice_cream":"🍨",
    "doughnut":"🍩",
    "cookie":"🍪",
    "chocolate_bar":"🍫",
    "candy":"🍬",
    "lollipop":"🍭",
    "custard":"🍮",
    "honey_pot":"🍯",
    "cake":"🍰",
    "bento":"🍱",
    "stew":"🍲",
    "egg":"🍳",
    "fork_and_knife":"🍴",
    "tea":"🍵",
    "sake":"🍶",
    "wine_glass":"🍷",
    "cocktail":"🍸",
    "tropical_drink":"🍹",
    "beer":"🍺",
    "beers":"🍻",
    "baby_bottle":"🍼",
    "knife_fork_plate":"🍽",
    "champagne":"🍾",
    "popcorn":"🍿",
    "ribbon":"🎀",
    "gift":"🎁"
  },
  popular: [{"tag":"sculpture","count":75},{"tag":"florence","count":47},{"tag":"portrait","count":41},{"tag":"blue","count":41},{"tag":"renaissance","count":40},{"tag":"landscape","count":37},{"tag":"gold","count":36},{"tag":"bird","count":35},{"tag":"dog","count":33},{"tag":"green","count":32},{"tag":"composition studies","count":31},{"tag":"horse","count":27},{"tag":"polearm","count":27},{"tag":"jesus","count":26},{"tag":"weapon","count":25},{"tag":"tempera","count":24},{"tag":"halberd","count":23},{"tag":"florentine","count":23},{"tag":"venice","count":22},{"tag":"armor","count":21},{"tag":"impressionist","count":21},{"tag":"woman","count":18},{"tag":"sword","count":18},{"tag":"red","count":17},{"tag":"steel","count":17},{"tag":"pagny","count":17},{"tag":"purple","count":17},{"tag":"european","count":17},{"tag":"french","count":16},{"tag":"landscape 19c","count":16},{"tag":"flowers","count":16},{"tag":"impressionism","count":16},{"tag":"furniture","count":15},{"tag":"music","count":15},{"tag":"peale","count":15},{"tag":"bust","count":14},{"tag":"siena","count":14},{"tag":"coat of arms","count":14},{"tag":"peale family","count":14},{"tag":"painting","count":13},{"tag":"mythology","count":13},{"tag":"spanish","count":13},{"tag":"chair","count":12},{"tag":"silver","count":12},{"tag":"arms and armor","count":12},{"tag":"disability","count":12},{"tag":"italian","count":12},{"tag":"child","count":12},{"tag":"glass","count":12},{"tag":"nhd 1815 to 1860 tools","count":12},{"tag":"animal","count":12},{"tag":"east asian art","count":12},{"tag":"angel","count":12},{"tag":"1500's","count":11},{"tag":"philadelphia artist","count":11},{"tag":"animals","count":11},{"tag":"baroque","count":11},{"tag":"african american art","count":11},{"tag":"late medieval","count":11},{"tag":"hindu","count":11},{"tag":"brass","count":11},{"tag":"love","count":10},{"tag":"charles wilson peale","count":10},{"tag":"still life","count":10},{"tag":"india","count":10},{"tag":"altarpiece","count":10},{"tag":"indian and himalayan art","count":10},{"tag":"religious","count":10},{"tag":"wunderkammer","count":10},{"tag":"france","count":10},{"tag":"seascape","count":9},{"tag":"virgin mary","count":9},{"tag":"bridge","count":9},{"tag":"black art","count":9},{"tag":"19th century","count":9},{"tag":"mary","count":9},{"tag":"deer","count":9},{"tag":"realism","count":9},{"tag":"valencia","count":9},{"tag":"water","count":9},{"tag":"european decorative arts and sculpture","count":9},{"tag":"medieval","count":9},{"tag":"dragon","count":9},{"tag":"monet","count":9},{"tag":"family","count":9},{"tag":"yellow","count":9},{"tag":"dutch","count":9},{"tag":"african american","count":9},{"tag":"african american artist","count":8},{"tag":"cezanne","count":8},{"tag":"nature","count":8},{"tag":"german","count":8},{"tag":"profile","count":8},{"tag":"royal","count":8},{"tag":"bible","count":8},{"tag":"nhd 1877 to 1900 portrait","count":8},{"tag":"european art 1100-1500","count":8},{"tag":"renoir","count":8},{"tag":"children","count":8},{"tag":"christ","count":8},{"tag":"sheep","count":7},{"tag":"snow","count":7},{"tag":"empire","count":7},{"tag":"cross","count":7},{"tag":"meiller","count":7},{"tag":"ferrara","count":7},{"tag":"lion","count":7},{"tag":"young friends","count":7},{"tag":"favorite","count":7},{"tag":"first empire","count":7},{"tag":"tapestry","count":7},{"tag":"interior","count":7},{"tag":"carved","count":7},{"tag":"deity","count":7},{"tag":"window","count":6},{"tag":"goddess","count":6},{"tag":"italy","count":6},{"tag":"netherlandish","count":6},{"tag":"miniature","count":6},{"tag":"tall case clock","count":6},{"tag":"neoclassic","count":6},{"tag":"vishnu","count":6},{"tag":"president","count":6},{"tag":"oil painting","count":6},{"tag":"tree","count":6},{"tag":"sunset","count":6},{"tag":"redware bird","count":6},{"tag":"pottery","count":6},{"tag":"oriental","count":6},{"tag":"trees","count":6},{"tag":"mother and child","count":6},{"tag":"cadwalader family","count":6},{"tag":"ceramic","count":6},{"tag":"time","count":6},{"tag":"boy","count":6},{"tag":"napoleon","count":6},{"tag":"cat","count":6},{"tag":"shield","count":6},{"tag":"nhd 1763 to 1783 portrait","count":6},{"tag":"buddhism","count":6},{"tag":"ganesha","count":6},{"tag":"oil on canvas","count":6},{"tag":"fruit","count":6},{"tag":"women","count":6},{"tag":"pink","count":6},{"tag":"sea","count":6},{"tag":"germany","count":6},{"tag":"rococo","count":6},{"tag":"flower","count":5},{"tag":"perspective","count":5},{"tag":"wealth","count":5},{"tag":"gupta","count":5},{"tag":"spain","count":5},{"tag":"helmet","count":5},{"tag":"pope","count":5},{"tag":"hunting","count":5},{"tag":"guardian","count":5},{"tag":"snake","count":5},{"tag":"marriage","count":5},{"tag":"15th century","count":5},{"tag":"vessel","count":5},{"tag":"hat","count":5},{"tag":"manet","count":5},{"tag":"elephant","count":5},{"tag":"rapier","count":5},{"tag":"storm","count":5},{"tag":"mannerism","count":5},{"tag":"nhd 1585 to 1763 portrait","count":5},{"tag":"heart","count":5},{"tag":"flemish","count":5},{"tag":"knight","count":5},{"tag":"birds","count":5},{"tag":"rabbit","count":5},{"tag":"winter","count":5},{"tag":"native american","count":5},{"tag":"relief","count":5},{"tag":"light","count":5},{"tag":"yum","count":5},{"tag":"cherubs","count":5},{"tag":"pagny-le-château","count":5},{"tag":"bologna","count":5},{"tag":"bronze","count":5},{"tag":"sun","count":5},{"tag":"period room","count":5},{"tag":"architecture","count":5},{"tag":"rooster","count":5},{"tag":"austrian","count":5},{"tag":"author","count":5},{"tag":"stoneware","count":5},{"tag":"duck","count":5},{"tag":"money bag","count":4},{"tag":"watercolor","count":4},{"tag":"gana","count":4},{"tag":"nhd 1815 to 1860 leisure ceramics","count":4},{"tag":"biblical stories","count":4},{"tag":"table","count":4},{"tag":"boat","count":4},{"tag":"compassion","count":4},{"tag":"nude","count":4},{"tag":"monkey","count":4},{"tag":"18th century","count":4},{"tag":"jewelry","count":4},{"tag":"praying","count":4},{"tag":"italian artist","count":4},{"tag":"fish","count":4},{"tag":"eagle","count":4},{"tag":"children's audio","count":4},{"tag":"vase","count":4},{"tag":"buckler","count":4},{"tag":"1500s","count":4},{"tag":"audio stop","count":4},{"tag":"baby","count":4},{"tag":"old testament","count":4},{"tag":"mountain","count":4},{"tag":"japan","count":4},{"tag":"river","count":4},{"tag":"rome","count":4},{"tag":"asia","count":4},{"tag":"mother","count":4},{"tag":"clouds","count":4},{"tag":"greyhound","count":4},{"tag":"directoire","count":4},{"tag":"nhd 1585 to 1763 armour","count":4},{"tag":"flask","count":4},{"tag":"western himalayan","count":4},{"tag":"ritual object","count":4},{"tag":"northern india","count":4},{"tag":"ritual water vessel","count":4},{"tag":"ritual","count":4},{"tag":"conch shell","count":4},{"tag":"trinity","count":4},{"tag":"odisha","count":4},{"tag":"west bengal","count":4},{"tag":"nhd 1877 to 1900 tools","count":4},{"tag":"sienese","count":4},{"tag":"mexico","count":4},{"tag":"madonna","count":4},{"tag":"crucifixion","count":4},{"tag":"nhd 1783 to 1815 portrait","count":4},{"tag":"porcelain","count":4},{"tag":"asian art","count":4},{"tag":"mahogany","count":4},{"tag":"jesus christ","count":4},{"tag":"triptych","count":4},{"tag":"paper","count":4},{"tag":"whistle","count":4},{"tag":"rattle","count":4},{"tag":"fire","count":4},{"tag":"northern european renaissance","count":4},{"tag":"16th century","count":4}],
  tags: ["1300s","1300s-1400s","13th century","1400's","1400s","1400s-1500s","14th century","1500's","1500s","1550 italian table","15th century","15th-16th century","1600's","1600s","16th century","1700s","1772","17th century","1846","1864","1867 universal exposition","1890","18th","18th century","1902 bruges exhibition","1903","19th century","19th century american artist","19th century realism","20th century","3 wise men","abduction","abington","aboriginie","abraham lincoln","abstract","abstraction","actually nanny and child","adam","adeline pepper gibson","adolescence","adoration","adrogynous","aeneid","aesthetic movement","affleck","africa","african american","african american art","african american artist","african warrior","agony","alabaster","alakues@hotmail.com","albany","alberti","alfred stevens","alfred-émile-léopold stevens","alkaline glaze","allegory","altar","altarpiece","ambiguous","america","american","american civil war","american friends of lafayette","american furniture","american painters","american rococo","american silver","american textiles","american vase","anatomy","andes","andrea ferrara","androgyn","androgynous","angel","angel of purity","angels","angle","angry and happy","anguish","animal","animals","ann clapham","anna claypoole peale","anne de montmorency","annenberg","annunciation","anonymous","anonymous artist","antichrist","antiquity","antwerp","apostle","apsaras","arabia","arabs","aragon","arch","archeiropoeton","archery","arches","archinto","architecture","arena","aristocracy","ark","armor","armour","arms and armor","army","arrow","art and craft","art nouveau","artemis","artpaper","arts","asia","asian","asian art","aspiring","assam","assassination","asymmetrical","athlete","atmosphere","atmospheric effects","attics","aubusson-rug","audio file","audio stop","augsburg","auguste rodin","austrian","author","autumn","avalokiteshvara","axes","baby","baby jesus","bacchus","balance","bald eagle","ballerina","ballet","bamboo","bank","banned","banners","barberini","barefoot","barooque","baroque","bat","bath","bather","bathers","battle","beach","bear","beards","bed chamber","bedchamber","bedroom","bedrooms","beds","beechwood","beer","belgian","belgian symbolism","bell","bellot","benedictine","bengali","benjamin franklin","bergamo","berger kabyle","berlin","bernardo daddi","betrothal","bhagavata purana","bhumispasa mudra (touching earth","bible","bible story","biblical","biblical stories","biblical story","bill","bird","bird bath","bird on flower basket","bird tree","bird-catching","birdcage","birds","birds of pennsylvania","birds on basket","birth of venus","black","black art","black figure","black robe","blacklivesmatter","blacks","blank face","bleak landscape","blended","blessed virgin","blood","blue","blue sky","blue-and-white porcelain","boat","boats","boccaccio","bodhi tree","bodhisattva","bodhisatva","body","body armor","bold","bologna","bonapartes","bones","bonnard","boon-granting (varada mudra)","boots","border","bosch","boulogne","bowl","boxer","boxing","boy","boy leaving home","branch","brass","brazil","breastfeeding","breastplate","brescia","bride","bridge","bright","brittany","brocade","broken-pediment","bronze","brooch","brooding","brook lenfest","brown","bruges","brush","brush painting","brussels","bubonic plague","buckler","buddha","buddhism","buddhist","buffalo","bull","buskin","bust","butt","butterfly","buttons","cabbage","cabinet","cadwalader","cadwalader family","cafe","calligraphy","callisto","calvary","camels","camera","candelabra","candles","candlestand","candrasala","cane","canine","canvas","cards","carmelite","carpet","carriage","carriage step","carriages","carrots","cart","carved","carved wood","carving","cassone","castle ashby","cat","catalan","cathedral","catholic","cattle","cauldron","cedar grove","celebration","cell","ceramic","ceramics","ceremony of tea","cezanne","cezanne series","chainmail","chair","chair rail","chairs","chandrashala","chanfron","chariot","charles willson peale","charles wilson peale","charpoy","chateau d'ecouen","chateau noir","check it out!","cherub","cherubs","chest","chiaroscuro","chicken","child","childbirth","childhood of christ","children","children's audio","children's crusade","china","chinese art","chinese artist","chinese porcelain","chola bronze","christ","christening","christian","christian richter","christian schuessele","christianity","christmas","church","circle","circus","city scene","cizhou ware","classical","classical revival style","claude","claude monet","clay","clenched","clergy","cliff","cliffs","clock","clouds","clowns","coast","coastal","coat of arms","cobbler","codpiece","coffee","coffee service","coffered ceiling","cogitating","cola","colisseum","collab","collector","cologne","colonial","colorfield","colorful bird","colorful birds","combat","coming of age","compassion","complementary color","complete","complete suit of armor","composer","composition","composition studies","compote","compount hilt","conceptualism","conch shell","conflagration","congressman","conjoined","conservation","constantine","contemplating","convivial","copper","copulation","corpulent","corpus","costume","couch","country","countryside","couple","courage","court","courtesan","courtly","courtship","courtsword","courtyard","cow","cowboy","cows","crab","cranach the elder","crate training","creepy","cremona","cremonese","crescent moon jewel","crew","cristóbal de villalpando","crone","cropped","crops","cross","crosses","crouching","crown","crucifix","crucifixion","cruelty","crying","css alabama","cubist","cultural landscape","cup and ball","cup-hilted rapier","cupid","curtain","curvy","customhouse","cut","cut-glaze decoration","cute ole goats","daffodills","dagger","daily life","dancer","dancing","dancing ganesha","dancing goddess","dandy","dante","dante chair","dark clouds","dark colors","dark pallette","dark sky","dark wood","de medici","dead animal","death","deaths head moths","decadence","decay","deceased","decorated vase","decorative","decorative arts","deer","deference","degas","degenerate","degenerate art","deity","delicate","demon","departure","design collection","destijl","destruction","devoted","devotional","diana","diety","dining","dinnerware","directoire","disability","dishes","divine","divine!","dog","dogga","dogs","doll","dolphin-footed chair","domenico ghirlandaio","domestic","domesticated animal","dominican","donkey","donor","donor panel","donor portrait","door","doorway","dove","dove of peace","doves","dowry chest","dragon","drama","dramatic","dramatic composition","drapery","drawing room","dreary","dress","dresses","drinking","drum","duck","duke of marlborough","durga","dusk","dutch","dutch artist","dutch genre","dutch painter","dutch porcelain","dutch tiles","duty","eagle","eakins","early","early baroque","early renaissance","earth","earthenware","easel","east asian art","east lothian","ebony","edgefield","edo period","edouard manet","edward hicks","edward hopper","eggs","egypt","eiffel tower","eighteenth century","elaborate","electra","elephant","elf","elijah","elite","embroidery","emilie ambre","emperor maximilian ii","empire","enamel","enamel and gilt porcelain","england","english","english artist","english bowl","english designer","engraving","enlightenment","entartete kunst","enthroned","epte river","equine","eros","escape","esther","etched","europe","european","european art","european art 1100-1500","european decorative arts and sculpture","evanescent joys","event","excellent label and additional information","exotic","exotic landscape","expensive","experiment","experimental","expressionism","extravagance","eye","fabriano","fabulous!","face","facebook","faerie","fairy","faith","fall 2008 final","family","fanciful","fancy","fantasy","farm","fashion","father","father time","favorite","favrile","favrile pottery","feather","federal","federalist","feline","female","female artist","female nude","female subject","feminism","fence","ferrara","fertility","festival","field","fighter","figulines rustiques","figure","figures","figurine","filtered light","final project","fiore","fire","fire screen","firearm","fireplace","fireplace surround","first empire","first family","fish","fisherman","flag","flaming sword","flask","flat planes","flatness","flemish","flock","floods","floral","florence","florentine","florentine painting","flower","flower crown","flowering tree","flowers","fog","folding chair","folk art","food","formal","foulc","founder","foundress philadelphia sisters of mercy 1861","four panels","four seasons","fragment","frame","frame-within-a-frame","france","franciscain","franciscan monastery","franciscans","franco prussian war","frankincense","freedom","french","french architecture","french artist","french earthenware","french literature","french painters","french salon","french sculpture","fruit","fuller","fun","funerary","furniture","gabriel","gallery 262","game","gamekeeper","gana","gandhara","ganesha","garden","gardua","garniture","garrets","garuda","gates of hell","gauguin","gauntlet","gazelle","geese","gems","gender","general jar","genesis","genoa","genre","genre scene","genre scenes","gentry","geometric","geometric abstraction","geometrical","geometry","george washington","georgian","german","german armor","german expressionism","german rapier","germanic","germany","gestures","gift","gifts","gilded","gilded cage","gilding","gilt furniture","ginger jar","giraffe","girl","girls","giverny","glass","glass decorated column","glass vase","glasses","glazed","globular","glove","glowing","gluttony","goat","goats","god","goddeses","goddess","gold","gold finch","gold leaf","gold leaf spain","gold-and-silver","golgotha","good","goodbye","gopi","gorham","gothic","goya","grand canyon","grape","grapes","graph","grass","grave","gravestone","gray","great britain","greece","greek mythology","green","green jade","green park","grey wig","greyhound","greyhounds","grieving","griffin","grover cleveland","growth","guard","guardian","guild","guitar","gupta","gypsy moth worm","hagley hall","hague school","halberd","hallmark","hand","hand-and-a-half sword","handkerchief","handle","hands","happy","hardedge","hardware","hare","harmony","harness","harp","hat","haunting","haussmannization","head","headpiece","headscarf","heart","heavy","heinrich keller","hellfire toasting glass","helmet","helmit","henry clay","herm","hermit","hermoso","hexagons","hicks","hierarchical proportion (inverse)","hieronymus bosch","high horizon","high renaissance","highlight","hindu","hindu deity","hindu temple","hip flask","historicism","holiday","holy family","holy roman emperor","holy roman emperor maximilian ii","hongloumeng (novel)","hongloumeng (novel)?","hope","horse","horses","hound","house","house of commons","house of lords","household item","houses","hovenden","human form","humanism","humanist","humiliation","humility","hungarian","hunt","hunter","hunting","hunting bag","hunting dog","icon","idol","ignorance","illusion","impasto","imperial","important","impressionism","impressionist","impressionistic","in charge","incense","inch worm","incised","independence hall","india","indian and himalayan art","indian art","indian art tour","indian manuscripts","industry","infant","infant christ","infant jesus","infant john the baptist","ingres","ink","ink on paper","inkwell","inlaid wood","innocence","innocent","inro","inscription","insect","inspirational","instruments","intercourse","interesting","interior","international gothic","interruption","intertwined","intimacy","invention","iridescent","iridescent column","iron","isaiah 11:6","islamic","islamic art","isolation","italian","italian artist","italian renaissance","italian scene","italian tempera painting","italian woman","italy","ivory","jabot","jacob","jade","jainism","james abbott mcneil whistler","james garfield","jan baegert","january","japan","japanese","japanese footbridge","japanese teahouse","japonisme","jar","jealousy","jesuit","jesus","jesus christ","jeweled","jewelery","jewelry","jewels","jewish","jews","john g. johnson collection","john la farge","john the baptist","johnson collection","josé campeche","jousting armor","jubé","jubée","judaic","judgement","judith de botton","jug","juliette hanson","jungle","kasia","kelley cadwallader","key","khajuraho","kids","kienbusch","king","king francis i of france","kingship","kissing birds","klee","kneeling","knight","knitting","konstanz","kramrisch","krishna","kuṇḍi","l'estaque","labyrinth","lack of atmospheric perspective","lacquer","ladder","ladies","lake","lake george","lalitasana (relaxed seated pose)","landmark","landscape","landscape 19c","landshut","lansdowne house","lantsha characters","large hands","last days","last supper","late medieval","late renaissance","latin america","latino art","lavish","lead","leaves","leaving","lecher","legend","leprosy","liberty bell","lidded jar","light","lightning","lily","lily pad","linear","linear perspective","lion","literary","little bo peep","little girl","lo spagnoletto","lobster","london","longsword","looking to write","lord","loss","lost wax","lost wax casting","lotus","lotus position","love","love story","loved it","lover to louis vx","lovers","lovesickness","loyalist","loyalty","lucy lewis","lustreware","luttichuys","madanagopalaswamy","madona stone archway","madonna","madurai","magi","mahogany","maille","maiolica","maitreya","make-believe","male","male artist","male subject","mamout","man","manet","mango","mannerism","mantle","mantle clock","maori","maple","marble","marble top","maria marchioness of northampton","marian","marie de' medici","maritime","market","marketplace","marquesas islands","marriage","mars","marseille","marseilles","marsh","marthe","martin johnson heade","martyr","mary","mary magdalene","mass","master of montelabate","masterpiece","mathematical","matriarchy","maturity","maximilian ii","mayhem","mcallister family","mcallister silver","meaningful","medici","medicine","medieval","medieval art","medieval period","meditation","meditative","meditator","meeting","meiller","memento mori","memling","men","mendelssohn","merged","metal","metalwork","metamorphoses","mexican","mexican artist","mexican iconography","mexico","milan","milanese","militarism","military","military leader","milk glass","milk jug","minerva","ming reception hall","miniature","miniatures","minimal","minister","minor dutch master","miracle","mirror","mirth","missionary","miyamoto musashi","mochi","modern","modernism","modernity","molded","mondrian","monet","monet series","monet's palate","money bag","monk","monkey","monochromatic","monogram","monotheism","monsieur","mont sainte-victoire","montante","moody","moor","moorish mufti","morality","morocco","mosaic","mosaic floors","mosaics","mosiac flooring","mother","mother and child","mother of god","mother-of-pearl","mount alverna","mount pleasant","mount vesuvius","mountain","mountains","mourning","mouse","moustache","mt saint-victoire","mug","muqarnas","museum","music","music room","musical instrument","musician","musicians","muslim","mustache","mutton chops","my great great great grandfather","my presentation","my tour","myrrh","mystery","myth","mythical","mythological","mythological character","mythology","nails","naive","nandi","naples","napolean","napoleon","nathaniel currier","national tragedy","native american","nativity","natural history","nature","nearly monochromatic","necklace","neo-plasticism","neoclassic","neoclassical","neoclassical portrait","neoclassicism","nesting","nesting bird","netherlandish","neutral colors","nhd 1585 to 1763 architecture","nhd 1585 to 1763 armour","nhd 1585 to 1763 portrait","nhd 1763 to 1783 architecture","nhd 1763 to 1783 commerce","nhd 1763 to 1783 food ceramics","nhd 1763 to 1783 portrait","nhd 1783 to 1815 architecture","nhd 1783 to 1815 ceramics","nhd 1783 to 1815 leisure ceramics","nhd 1783 to 1815 portait","nhd 1783 to 1815 portrait","nhd 1783 to 1815 tools","nhd 1815 to 1860","nhd 1815 to 1860 architecture","nhd 1815 to 1860 ceramics","nhd 1815 to 1860 ceramics leisure","nhd 1815 to 1860 commerce","nhd 1815 to 1860 culture","nhd 1815 to 1860 food","nhd 1815 to 1860 food ceramics","nhd 1815 to 1860 leisure ceramics","nhd 1815 to 1860 portrait","nhd 1815 to 1860 portrait washington","nhd 1815 to 1860 rural","nhd 1815 to 1860 tools","nhd 1861 to 1877","nhd 1861 to 1877 food ceramics","nhd 1861 to 1877 leisure ceramics","nhd 1861 to 1877 portrait","nhd 1861 to 1877 tools","nhd 1861 to 1877 urban","nhd 1861 to 1900 rural","nhd 1877 to 1900 ceramics","nhd 1877 to 1900 culture","nhd 1877 to 1900 entertainment","nhd 1877 to 1900 portrait","nhd 1877 to 1900 rural","nhd 1877 to 1900 tools","nhd 1877 to 1900 urban","nhd 1883 to 1900 portrait","nhd 1900 to 1929 ceramics","nhd 1900 to 1929 portrait","nhd 1929 to 1945 tools","niche","niece charles peale","night","nightgown","nilan","niomon","noah","non-duality","non-objective","nonviolence","normandy","north africa","northern european","northern european renaissance","northern india","nottingham","nouveau","nude","nudity","null","nun","nursing virgin","oak","oakeshott type xi","oath","oboe","obstentation","ocean","octagonal","oculus","ode to bacchus","odisha","officer","oil","oil on canvas","oil on panel","oil painting","oil sketch","old testament","old woman","olive","olympus","opalescent glass","opals","open windows","openwork","optic molded","optical illusion","orange","oriental","oriental rug","orientalism","orientalist","original hipster","ornate","ornate carving","ottomans","ouch","outdoors","outlander fans","outside","ovid","owl","padua","pagan","pagan processional","pagny","pagny-le-château","paint","painted","painted bird","painted glass","painted underglaze","painter to marie antoinette","painting","painting within a painting","paintings","pair of birds","pakistan","pala","palace ladies","pale","palette knife","palm tree","palm trees","panel","panel paintings","panels","paper","paradise","paradise garden","paris","parisian","park","parliament","parma","paron's pleasure","parquet","parrot","parrying dagger","parting","partnership","parvati","passau","passengers","passion","pastoral","path","patron","patron of arts","patron of laborers","patron portrait","patron saints","pattern","pavise","pax","peace","peach","peaches","peafoul","peale","peale family","pearls","peasant","pedestal","pen painting","pennsylvania artist","pennsylvania german","pennsylvania vase","pentimento","peonies","people","perceive sound","perching bird","performer","performing","performing arts","period room","persia","persian","persian mosaics","perspectival shift","perspective","pet","peter paul rubens","pheasant","philadelphia","philadelphia artist","philadelphia silver","philadelphian","piano","picchwai","pickle","pictorialism","picture plane","picture-plane","picturesque","piedmont","pierced","pieta","pietro lorenzetti","piety","pig","piggy bank","pigs","pike","pin","pine","pine bird","pine birds","pines","pink","pinnacle","pipe","pitcher","pitkin ink","plaster bird","plate","play","play-acting","players","playing","playing cards","pleasures","poet","poetry","pointillism","pole arms","polearm","poleaxe","policeman","politician","pollaxe","polychrome","pommel","pompeii","pond","pont neuf","pope","poplar trees","poplars","porcelain","portrait","portrait of mr. adyes children","portuguese","poseidon","posing","post impressionism","postage stamp","poster","pottery","poussin","powder flask","powdered hair","prato","prayer book","praying","pre-daoist mythology","predella","president","priest","primary","primary colors","primavera","procession","processional","profile","promenade","prophet","proposition","providence","puberty","puebla","puerto rico","punch","puppy","purim","purity","purple","putti","putto","qing dynasty","quail","quaker","quaker artist","quartz","quattrocento","queen","queen of france","quilt","quilts","rabbit","raccoon","rain","rainbow","rajasthan","ram","rama","ramayana","rapier","rare","rattle","reading","realism","realist","realistic","reconciliation","red","red herring","redemption","redware","redware bird","redware vase","refined","reflection","reflections","relic","relief","relief sculpture","religion","religious","reliquary","rembrandt","renaissance","renoir","repetition","repousse","respect","rest from the hunt","resurrection","reticulated","revolution","revolutionary war","rhythm","ribbed","riding","rifle","rilievo schiacciato","rilievo stiacciato","ring","ritual","ritual object","ritual water vessel","river","rivulet","road","roald dahl","robert adam","rockingham","rocks","rococo","rodin","role-playing","roman column","roman emperor","roman emperor maximilian ii","roman history","romance","romantic","romanticism","rome","rondels","roosevelt","rooster","rosette","rowing","royal","ruffles","rug","rugs","ruskin","rustic","rustic earthenware","rustic nature","sabine","sacred","sacred conversation","sacrifice","sad","sadness","sail boat","sailboat","sailing","saint anne","saint elizabeth","saint francis","saint nicholas","saint peter","saint-cloud","saints","salon","salvation","sandstone","satire","satire of venus' chariot","satyr","savage","savior","savonarola","saxony","scabbard","scalloped","scannabecci","scholar","scholl","school","science","scotland","scottish","scroll","scrolls","sculptor","sculpture","sea","sea shell","seascape","seashell","seaside","seasons","seated figure","seated figures","see-saw","seesaw","segmented","seine","self portrait","selvedge","sensual","seraglio","serene","serene interior","serenity","series","serpent","seven eyes","seville","sfondagiaco","shaffron","shaker","shawl","sheep","shell","shells","shield","ship","shiva","shoe","sholder firelock","shroud","sibling","siblings","siena","sienese","sienese painting","sienese school","silenus","silhouette","silk","silver","silver replica","similarity","singing","sinkler","siren","sisley","skeleton","skull","skulls","sky","slavery","smallsword","smoke stack","smoking","smooth","snake","snakes","snow","snowshoe","sodden","solar","soldier","soldier ant","soldiers","solstice","somber","son","song","sorolla","sorrow","south asia","south asian art","south carolina","south of france","spain","spalliera","spaniards","spanish","spanish artists","spanish primitive","sparrow","speckled bird","sphinxes","spindle","spindle whorl","spinning","spinning wheel","spirals","spiritual","sport","sports","spout","spring","square","squirrel","st. francis of assisi","st. helena","st. joseph","st. terasea of the little flower","stabbing","stable","stag","stage","stained","stained glass","standing","standing sculpture","star","statue","status","steam","steel","still life","stone","stonemasons","stoneware","storage jar","stork","storm","stormy","storybook","stove","strange portrait","strength","strike-a-pose","striped wallpaper","stripes","struggles","student","students","studio","sudarium","sufi","summer","sun","sundial","sunflower","sunkaraku","sunlight","sunrise","sunset","surrealism","swabia","swagger","swat valley","swoon","sword","swords","symbolism","symbolist","table","tableware","tahiti","talavera","talismanic","tall case clock","tambourine","tamil nadu","tamilnadu","taoism","tapestries","tapestry","tassels","tassle","tavern","tea","tea house","teabowl","teacher resources","teaching","teeter-totter","tempera","tempera and gold","temperance","tempest","temple","temple wall","tenderness","tenebrism","tennis","tension","text","textile","texture","thangka","the adam style","the battle of athelstaneford","the colors","the george h. lorimer collection","the mocking of christ","the netherlands","the saltire cross","the southwest","theatrum pictorium","thesis","thin","third eye","thomas wright","thorn","three","three dimensional","throne","tibetan","tiffany architecture","tile","tiles","tilting","time","titian","tomb","tombstone","tondo","tools","top hat","toreador","torero","torture","touching earth (bhumisparsa mudra)","tournai","tournaments","town","toy","toy soldier","toys","traffic","train","tranquility","tree","tree stump","trees","trident","trinity","triptych","trishula","triumph","trojan war","trompe l’oeil","tropical","tropical flora","tropical landscape","troubador","trumpet","tucker","tulip","tulips","turner","turquoise","tuscany","twilight","twisting column","two girls","two-faced","tyranny","uma","umbria","umbrian","underground","unicorn","united states","unity","unknown artist","unorthodox iconography","upholstered","urban scene","us artist","us south","us-born artist","uss kearsarge","utopian","valencia","vallabhacharya","van gogh","vanitas","varada mudra (boon-granting)","varengeville","vase","vegetable","veil","velvet","venetian","venetian renaissance","venice","venus","verdancy","vermeer","vernon","vernonnet","verona","veronese","vessel","vice president","vicscottiii","victorian","victorian era","victrola","view","village","vines","violinist","virgil","virgin","virgin and child","virgin mary","virtue","vishnu","vista","volterra","vow","vrindavan","walker","walking stick","wall","wallpaper","walls","walnut","want to use the oxen pulling boat","war","warfare","warm light","wassup my migga","water","water fall","watercolor","waterfall","waves","wealth","weapon","weapons","weather","weather vane","weaving","wedding","wedding party","wedgewood-like","weeping","weeping willow","west bengal","western himalayan","western tibet","westphalia","wet","whale","wheels","whirlwind","whistle","whistler","whistler's mother","whistling bird","white","white crocus'","wife","wild animal","william maw egley","windmill","window","windows","wine","wine glass","wings","winter","wire","woman","woman going to market","woman subject","women","women's committee","wood","wood carving","wood paneling","wooden chair","worcestershire","worship","writhen","writing","wunderkammer","wwi","x-chair","yakshi","yamuna","yellow","yellow jacket bee","yellowteam2017","yoga","young friends","young girl","yum","zebra","zhejiang","écorché","épée","建窑","弘治","德化","明","水月观音","白瓷","白釉","素三彩","茶壶","茶杯","茶盏","葫芦瓶","軍持","过海观音","黄釉"]
}
